import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { buildQuestionnairePdfModel } from '@/components/pro-form/pdf/questionnairePdfModel';
import {
  buildQuestionnairePdfHtml,
  createQuestionnairePdfContainer
} from '@/components/pro-form/pdf/questionnairePdfTemplate';

const {
  addImageMock,
  html2canvasMock,
  jsPdfConstructorMock,
  saveMock,
  toDataUrlMock,
  trackClarityEventMock
} = vi.hoisted(() => {
  const addImage = vi.fn();
  const save = vi.fn();
  const toDataUrl = vi.fn(() => 'data:image/png;base64,questionnaire');
  const constructor = vi.fn(function jsPdfConstructor(options) {
    this.options = options;
    this.addImage = addImage;
    this.save = save;
  });

  return {
    addImageMock: addImage,
    html2canvasMock: vi.fn(),
    jsPdfConstructorMock: constructor,
    saveMock: save,
    toDataUrlMock: toDataUrl,
    trackClarityEventMock: vi.fn()
  };
});

vi.mock('html2canvas', () => ({ default: html2canvasMock }));
vi.mock('jspdf', () => ({ jsPDF: jsPdfConstructorMock }));
vi.mock('@/lib/clarity', () => ({ trackClarityEvent: trackClarityEventMock }));

import { generatePDF } from '@/components/pro-form/PDFGenerator';

const makeModel = (formData = {}) => buildQuestionnairePdfModel({
  formData,
  businessName: 'Acme IT',
  domain: 'acme.example',
  submissionDate: '2026-08-03'
});

const renderTemplate = (formData = {}) => {
  const wrapper = document.createElement('div');
  wrapper.innerHTML = buildQuestionnairePdfHtml(makeModel(formData), {
    logoUrl: '/assets/msp-success-digital-logo.svg'
  });
  document.body.appendChild(wrapper);
  return wrapper;
};

describe('questionnaire PDF DOM template', () => {
  afterEach(() => {
    document.body.innerHTML = '';
  });

  it('renders all 33 rows, all eight child rows, and the required section order', () => {
    const wrapper = renderTemplate();
    const rows = [...wrapper.querySelectorAll('[data-question-id]')];
    const childRows = wrapper.querySelectorAll('.questionnaire-pdf-row--child');
    const bars = [...wrapper.querySelectorAll('.questionnaire-pdf-section-bar')]
      .map((bar) => bar.textContent.trim());

    expect(rows).toHaveLength(33);
    expect(childRows).toHaveLength(8);
    expect(rows.at(-1).dataset.questionId).toBe('25.1');
    expect(bars).toEqual([
      'Business Information',
      'Additional Page Options',
      'About Your Business',
      'About Your Target Clients'
    ]);
  });

  it('uses the reference header, two-column layout, minimum heights, and local logo', () => {
    const html = buildQuestionnairePdfHtml(makeModel(), {
      logoUrl: '/assets/msp-success-digital-logo.svg'
    });

    expect(html).toContain('width: 612pt');
    expect(html).toContain('min-height: 4356pt');
    expect(html).toContain('grid-template-columns: 1fr 2fr');
    expect(html).toContain('grid-template-columns: 1fr 1fr');
    expect(html).toContain('background: #6464FF');
    expect(html).toContain('background: #ECECFF');
    expect(html).toContain('border-left: 3pt solid #6464FF');
    expect(html).toContain('--questionnaire-row-min-height: 175pt');
    expect(html).toContain('src="/assets/msp-success-digital-logo.svg"');
    expect(html).toContain('<span>Website Content</span><br /><span>Questionnaire</span>');
    expect(html).toContain('MSP Success - Pro Service');
  });

  it('keeps unanswered cells blank and excludes prohibited template artifacts', () => {
    const wrapper = renderTemplate();
    const answers = [...wrapper.querySelectorAll('.questionnaire-pdf-answer-cell')];
    const html = wrapper.innerHTML;

    expect(answers.every((cell) => cell.textContent === '')).toBe(true);
    expect(html).not.toMatch(/Not answered|N\/A|Response:|undefined|\[object Object\]/i);
    expect(html).not.toMatch(/gradient|border-radius|box-shadow|questionnaire-pdf-footer/i);
    expect(html).not.toMatch(/page number|Generated by MSP Success/i);
  });

  it('escapes HTML-like answers and preserves special characters and line breaks as text', () => {
    const dangerous = '<script>window.__pdfExecuted = true</script> & "quoted"\nApostrophe\'s';
    const wrapper = renderTemplate({ '6': dangerous });
    const answer = wrapper.querySelector('[data-question-id="6"] .questionnaire-pdf-answer-cell');

    expect(wrapper.querySelector('script')).toBeNull();
    expect(window.__pdfExecuted).toBeUndefined();
    expect(answer.textContent).toBe(dangerous.replace('\n', ''));
    expect(answer.innerHTML).toContain('&lt;script&gt;');
    expect(answer.innerHTML).toContain('<br>');
  });

  it('keeps child rows present while suppressing stale child answers for a non-Yes parent', () => {
    const wrapper = renderTemplate({
      '23': 'no',
      '23.1': 'Stale hidden response'
    });
    const child = wrapper.querySelector('[data-question-id="23.1"]');

    expect(child).not.toBeNull();
    expect(child.querySelector('.questionnaire-pdf-answer-cell').textContent).toBe('');
    expect(wrapper.textContent).not.toContain('Stale hidden response');
  });

  it('creates a reusable offscreen render root without appending it implicitly', () => {
    const container = createQuestionnairePdfContainer({
      model: makeModel(),
      logoUrl: '/assets/msp-success-digital-logo.svg'
    });

    expect(container.dataset.questionnairePdfRenderRoot).toBe('true');
    expect(container.isConnected).toBe(false);
    expect(container.querySelectorAll('[data-question-id]')).toHaveLength(33);
  });
});

describe('generatePDF browser rendering contract', () => {
  beforeEach(() => {
    document.body.innerHTML = '';
    addImageMock.mockReset();
    html2canvasMock.mockReset();
    jsPdfConstructorMock.mockClear();
    saveMock.mockReset();
    toDataUrlMock.mockClear();
    trackClarityEventMock.mockReset();

    vi.spyOn(HTMLImageElement.prototype, 'complete', 'get').mockReturnValue(true);
    vi.spyOn(HTMLImageElement.prototype, 'naturalWidth', 'get').mockReturnValue(782);
    Object.defineProperty(HTMLImageElement.prototype, 'decode', {
      configurable: true,
      value: vi.fn().mockResolvedValue(undefined)
    });
    vi.spyOn(HTMLElement.prototype, 'scrollWidth', 'get').mockReturnValue(816);
    vi.spyOn(HTMLElement.prototype, 'scrollHeight', 'get').mockReturnValue(5808);
    Object.defineProperty(document, 'fonts', {
      configurable: true,
      value: {
        load: vi.fn().mockResolvedValue([]),
        ready: Promise.resolve()
      }
    });

    html2canvasMock.mockResolvedValue({
      width: 1500,
      height: 10_676,
      toDataURL: toDataUrlMock
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    document.body.innerHTML = '';
  });

  it('builds one 612pt custom page, saves it, tracks success, and removes the render root', async () => {
    const result = await generatePDF(
      { '1': 'yes', '1.1': 'A representative answer', '25': 'no' },
      'Acme, IT',
      'acme.example'
    );
    const capturedDocument = html2canvasMock.mock.calls[0][0];
    const canvasOptions = html2canvasMock.mock.calls[0][1];
    const pdfOptions = jsPdfConstructorMock.mock.calls[0][0];

    expect(result).toMatchObject({ success: true });
    expect(result.filename).toMatch(/^AcmeIT_KaseyaWebsite_ContentQuestionnaire_Responses_\d{1,2}-\d{1,2}-\d{2}\.pdf$/);
    expect(capturedDocument.querySelectorAll('[data-question-id]')).toHaveLength(33);
    expect(capturedDocument.textContent).toContain('A representative answer');
    expect(capturedDocument.querySelector('[data-questionnaire-pdf-logo]').src)
      .toMatch(/^data:image\/png;base64,/);
    expect(canvasOptions.useCORS).toBe(false);
    expect(canvasOptions.scale).toBeGreaterThanOrEqual(1.8);
    expect(pdfOptions.unit).toBe('pt');
    expect(pdfOptions.format[0]).toBe(612);
    expect(pdfOptions.format[1]).toBeCloseTo(4356, 0);
    expect(addImageMock).toHaveBeenCalledTimes(1);
    expect(saveMock).toHaveBeenCalledWith(result.filename);
    expect(trackClarityEventMock).toHaveBeenCalledWith(
      'pro_questionnaire_pdf_downloaded',
      { business_domain: 'acme.example' }
    );
    expect(saveMock.mock.invocationCallOrder[0])
      .toBeLessThan(trackClarityEventMock.mock.invocationCallOrder[0]);
    expect(document.querySelector('[data-questionnaire-pdf-render-root]')).toBeNull();
  });

  it('removes the render root and does not fire Clarity when capture fails', async () => {
    vi.spyOn(console, 'error').mockImplementation(() => {});
    html2canvasMock.mockRejectedValue(new Error('capture failed'));

    const result = await generatePDF({ '6': 'Private response' }, 'Acme IT', 'acme.example');

    expect(result).toEqual({ success: false, error: 'capture failed' });
    expect(saveMock).not.toHaveBeenCalled();
    expect(trackClarityEventMock).not.toHaveBeenCalled();
    expect(document.querySelector('[data-questionnaire-pdf-render-root]')).toBeNull();
  });

  it('does not fire Clarity and still cleans up when saving fails', async () => {
    vi.spyOn(console, 'error').mockImplementation(() => {});
    saveMock.mockImplementation(() => {
      throw new Error('save failed');
    });

    const result = await generatePDF({}, 'Acme IT', '');

    expect(result).toEqual({ success: false, error: 'save failed' });
    expect(trackClarityEventMock).not.toHaveBeenCalled();
    expect(document.querySelector('[data-questionnaire-pdf-render-root]')).toBeNull();
  });

  it('does not accumulate hidden render roots across repeated downloads', async () => {
    await generatePDF({}, 'Acme IT', 'acme.example');
    await generatePDF({}, 'Acme IT', 'acme.example');

    expect(html2canvasMock).toHaveBeenCalledTimes(2);
    expect(document.querySelectorAll('[data-questionnaire-pdf-render-root]')).toHaveLength(0);
  });
});
