import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, RefreshCw } from 'lucide-react';
import { createProDraftHealthClient } from '@/lib/proDraftHealthClient';
import { useProDraftAdminAuthorization } from '@/hooks/useProDraftAdminAuthorization';

const percent = (value) => `${((Number(value) || 0) * 100).toFixed(2)}%`;
const statusClass = (status) => status === 'healthy' ? 'text-green-700' : status === 'disabled' ? 'text-slate-600' : 'text-amber-700';

/** @param {{client?: any}} props */
export default function ProDraftOperationsDashboard(props = {}) {
  const clientProp = props.client;
  const authorization = useProDraftAdminAuthorization(); const [data, setData] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [probeRunning, setProbeRunning] = useState(false); const [criticalOffset, setCriticalOffset] = useState(0);
  const client = useMemo(() => clientProp ?? createProDraftHealthClient({authorization: {getGrantForAuthorizedRequest: authorization.getAdminGrantForAuthorizedRequest}}), [clientProp, authorization.getAdminGrantForAuthorizedRequest]);
  const load = useCallback(async (offset) => { setLoading(true); setError(null); try { setData(await client.getAdminHealth({criticalOffset: offset})); } catch (reason) { setError(reason); } finally { setLoading(false); } }, [client]);
  useEffect(() => { void load(criticalOffset); }, [criticalOffset, load]);
  const runProbe = async () => { setProbeRunning(true); setError(null); try { await client.runSyntheticProbe({includeSubmittedStep: false}); await load(criticalOffset); } catch (reason) { setError(reason); } finally { setProbeRunning(false); } };
  if (loading && !data) return <main className="mx-auto max-w-7xl p-6" aria-busy="true"><p>Loading operational health…</p></main>;
  if (error && !data) return <main className="mx-auto max-w-7xl p-6"><h1 className="text-2xl font-bold">Draft Operations</h1><div role="alert" className="mt-4 rounded border border-red-300 bg-red-50 p-4">{error.message}</div><button type="button" className="mt-4 rounded bg-slate-900 px-4 py-2 text-white" onClick={() => load(criticalOffset)}>Retry</button></main>;
  const metrics = data?.metrics ?? {}; const components = data?.components ?? []; const critical = data?.criticalEvents ?? [];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">Draft Operations</h1><p className="text-sm text-slate-600">Safe aggregate health for {data.environment}; build {data.buildSha || 'unknown'}.</p></div><div className="flex gap-2"><button type="button" className="inline-flex items-center rounded border px-4 py-2 disabled:opacity-50" onClick={() => load(criticalOffset)} disabled={loading}><RefreshCw className="mr-2 h-4 w-4" aria-hidden="true" />Refresh</button><button type="button" className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50" onClick={runProbe} disabled={probeRunning}>{probeRunning ? 'Running probe…' : 'Run synthetic probe'}</button></div></header>
    {error ? <div role="alert" className="rounded border border-amber-300 bg-amber-50 p-3">{error.message}</div> : null}
    <section aria-labelledby="overall-health"><h2 id="overall-health" className="text-lg font-semibold">Overall health</h2><div className={`mt-2 flex items-center gap-2 text-xl font-semibold ${statusClass(data.status)}`}>{data.status === 'healthy' ? <CheckCircle2 aria-hidden="true" /> : <AlertTriangle aria-hidden="true" />}<span>{data.status}</span></div></section>
    <section aria-labelledby="service-components"><h2 id="service-components" className="text-lg font-semibold">Components</h2><div className="mt-2 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Current durable draft service component status</caption><thead><tr><th scope="col" className="border p-2">Component</th><th scope="col" className="border p-2">Status</th><th scope="col" className="border p-2">Safe code</th></tr></thead><tbody>{components.map((item) => <tr key={item.component}><th scope="row" className="border p-2 font-medium">{item.component}</th><td className={`border p-2 ${statusClass(item.status)}`}>{item.status}</td><td className="border p-2 font-mono text-xs">{item.errorCode || '—'}</td></tr>)}</tbody></table></div></section>
    <section aria-labelledby="operational-metrics"><h2 id="operational-metrics" className="text-lg font-semibold">Operational metrics</h2><dl className="mt-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Save p95', `${metrics.saveP95LatencyMs ?? '—'} ms`], ['Save p99', `${metrics.saveP99LatencyMs ?? '—'} ms`], ['Save error rate', percent(metrics.saveFailureRate)], ['Recovery failure rate', percent(metrics.recoveryFailureRate)], ['Conflict rate', percent(metrics.conflictRate)], ['Submission failure rate', percent(metrics.submissionFailureRate)], ['SES failure rate', percent(metrics.sesFailureRate)], ['Cleanup failures', metrics.cleanupFailureCount ?? 0]].map(([label, value]) => <div key={label} className="rounded border bg-white p-3"><dt className="text-sm text-slate-600">{label}</dt><dd className="text-xl font-semibold">{value}</dd></div>)}</dl></section>
    <section aria-labelledby="probe-status"><h2 id="probe-status" className="text-lg font-semibold">Last synthetic probe</h2><p className="mt-2">{data.lastSyntheticProbe ? `${data.lastSyntheticProbe.status} at ${data.lastSyntheticProbe.checkedAt}` : 'No probe evidence is available.'}</p></section>
    <section aria-labelledby="critical-events"><h2 id="critical-events" className="text-lg font-semibold">Critical events</h2><div className="mt-2 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Paginated safe critical operational events</caption><thead><tr><th scope="col" className="border p-2">Type</th><th scope="col" className="border p-2">Status</th><th scope="col" className="border p-2">Time</th><th scope="col" className="border p-2">Request</th></tr></thead><tbody>{critical.length ? critical.map((event, index) => <tr key={`${event.requestId}-${index}`}><td className="border p-2">{event.eventType}</td><td className="border p-2">{event.status}</td><td className="border p-2">{event.checkedAt}</td><td className="border p-2 font-mono text-xs">{event.requestId || '—'}</td></tr>) : <tr><td colSpan={4} className="border p-3 text-slate-600">No critical events in this page.</td></tr>}</tbody></table></div><nav aria-label="Critical event pages" className="mt-3 flex gap-2"><button type="button" className="rounded border px-4 py-2 disabled:opacity-50" disabled={criticalOffset === 0} onClick={() => setCriticalOffset((offset) => Math.max(0, offset - 20))}>Previous</button><button type="button" className="rounded border px-4 py-2 disabled:opacity-50" disabled={!data.criticalPagination?.hasMore} onClick={() => setCriticalOffset((offset) => offset + 20)}>Next</button></nav></section>
    <section aria-labelledby="feature-flags"><h2 id="feature-flags" className="text-lg font-semibold">Feature flags and configuration</h2><p className="text-sm text-slate-600">Only safe modes and presence booleans are shown; secret values are never returned.</p><ul className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries({...data.featureFlags, ...data.requiredSecretsPresent}).map(([name, value]) => <li key={name} className="rounded border bg-white p-2"><span className="font-mono text-xs">{name}</span>: {typeof value === 'boolean' ? value ? 'enabled/configured' : 'disabled/missing' : value}</li>)}</ul></section>
  </main>;
}
