// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface ProFormDraft {
  /**
   * Stable questionnaire session ID
   */
  session_id: string;
  /**
   * Business name associated with the draft
   */
  business_name?: string;
  /**
   * Business domain associated with the draft
   */
  domain?: string;
  /**
   * Client user ID if available
   */
  user_id?: string;
  /**
   * Client user name if available
   */
  user_name?: string;
  /**
   * Client user email if available
   */
  user_email?: string;
  /**
   * Draft lifecycle status
   */
  status?: string;
  /**
   * Currently active question ID
   */
  current_question_id?: string;
  /**
   * Last changed question ID
   */
  last_changed_question_id?: string;
  /**
   * Serialized questionnaire responses
   */
  responses_json?: string;
  /**
   * Serialized validation status map
   */
  validation_status_json?: string;
  /**
   * Serialized touched questions map
   */
  touched_questions_json?: string;
  /**
   * Serialized expanded questions map
   */
  expanded_questions_json?: string;
  /**
   * JSON string of mapped final payload metadata
   */
  metadata_json?: string;
  /**
   * JSON string of mapped final payload userdata
   */
  userdata_json?: string;
  /**
   * JSON string of full mapped final-style questionnaire payload
   */
  mapped_payload_json?: string;
  /**
   * Technical draft autosave metadata such as page path, source, and user agent
   */
  draft_metadata_json?: string;
  /**
   * Latest draft save error message
   */
  save_error?: string;
  /**
   * Latest submit error payload
   */
  submit_error?: string;
  /**
   * When final submit was attempted
   */
  submit_attempted_at?: string;
  /**
   * When final submit succeeded
   */
  submitted_at?: string;
  /**
   * When the last answer changed
   */
  last_changed_at?: string;
  /**
   * When the draft was last saved
   */
  last_saved_at?: string;
  /**
   * Linked final submission ID
   */
  final_submission_id?: string;
  /**
   * Current AI repair lifecycle status for this draft (e.g. pending, running, completed, failed, skipped)
   */
  ai_repair_status?: string;
  /**
   * ISO timestamp of the most recent AI repair attempt for this draft
   */
  last_ai_repair_at?: string;
  /**
   * Serialized error details if the AI repair attempt for this draft failed
   */
  ai_repair_error_json?: string;
  /**
   * Full JSON report returned by the pro_submission_repair_agent for this draft
   */
  ai_repair_report_json?: string;
  /**
   * Serialized repaired payload produced by the pro_submission_repair_agent for this draft
   */
  ai_repaired_payload_json?: string;
  /**
   * True if the AI-repaired payload was accepted and used in a submission attempt for this draft
   */
  ai_repair_applied?: boolean;
  /**
   * When this draft was moved out of the active recovery dataset
   */
  archived_at?: string;
  /**
   * Policy or administrator reason for archiving this draft
   */
  archive_reason?: string;
}

export interface ProFormDraftEvent {
  /**
   * Linked questionnaire session ID
   */
  session_id: string;
  /**
   * Draft activity event type
   */
  event_type?: string;
  /**
   * Question identifier
   */
  question_id?: string;
  /**
   * Question field type
   */
  question_type?: string;
  /**
   * Serialized event value
   */
  value_json?: string;
  /**
   * Human-friendly value summary
   */
  value_summary?: string;
  /**
   * Value length or serialized length
   */
  value_length?: number;
  /**
   * Count of selected options or values
   */
  selected_option_count?: number;
  /**
   * Business name for the session
   */
  business_name?: string;
  /**
   * Business domain for the session
   */
  domain?: string;
  /**
   * Client user ID if available
   */
  user_id?: string;
  /**
   * When the event was created
   */
  created_at_iso?: string;
}

export interface ProFormSubmission {
  metadata: {
    /**
     * The business name
     */
    business_name?: string;
    /**
     * The business domain
     */
    businessDomain?: string;
    /**
     * When the form was submitted
     */
    submission_datetime?: string;
    /**
     * The service tier (pro, essentials, etc.)
     */
    service_type?: string;
  };
  userdata: {
    /**
     * Optional additional pages configuration
     */
    additional_pages_list?: {
      why_choose_us_page?: {
        /**
         * If true, generate a Why Choose Us page. Based on Q1.
         */
        generate_page?: boolean;
        /**
         * Q1.1: Description for the Why Choose Us page
         */
        why_choose_us_description?: string;
      };
      meet_the_team_page?: {
        /**
         * If true, generate a Meet the Team page. Based on Q2.
         */
        generate_page?: boolean;
        /**
         * Q2.1: Introduction text for the Meet the Team page
         */
        team_introduction?: string;
        /**
         * Q2.2: Team photo and tagged team members
         */
        team_photo_with_tags?: {
          /**
           * URL of the team photo
           */
          imageUrl?: string;
          /**
           * Array of team members tagged in the photo
           */
          taggedPeople?: {
            /**
             * Team member's name
             */
            name?: string;
            /**
             * Team member's position/title
             */
            position?: string;
            /**
             * Team member's biography
             */
            bio?: string;
            /**
             * X coordinate of tag on image
             */
            x?: number;
            /**
             * Y coordinate of tag on image
             */
            y?: number;
          }[];
        };
      };
    };
    /**
     * Q3: Selected service offerings from predefined list
     */
    service_offerings?: string[];
    /**
     * Q3: Custom service offerings not in predefined list
     */
    service_offerings_other?: string;
    /**
     * Q4: Selected target industries from predefined list
     */
    target_industries?: string[];
    /**
     * Q4: Custom target industries not in predefined list
     */
    target_industries_other?: string;
    /**
     * Q5: Geographic areas served with location metadata
     */
    geographic_areas?: {
      geographic_area_meta?: {
        /**
         * Location name
         */
        name?: string;
        /**
         * Full location label
         */
        label?: string;
        /**
         * Latitude
         */
        lat?: string;
        /**
         * Longitude
         */
        lon?: string;
        /**
         * Google Places ID
         */
        place_id?: string;
        /**
         * Data source (e.g., 'google')
         */
        source?: string;
        /**
         * True if this is the primary service location
         */
        primary?: boolean;
      };
    }[];
    /**
     * Q6: Company description and history
     */
    company_description?: string;
    /**
     * Q7: How services are delivered (on-site, remote, hybrid)
     */
    delivery_model?: string;
    /**
     * Q7: Custom delivery model if 'Other' was selected
     */
    delivery_model_other?: string;
    /**
     * Q8: Pricing and packaging models
     */
    pricing_packaging?: string[];
    /**
     * Q8: Custom pricing model if 'Other' was selected
     */
    pricing_packaging_other?: string;
    /**
     * Q9: What makes the company different from competitors
     */
    differentiation?: string;
    /**
     * Q10: Company goals for the website
     */
    company_goals?: string[];
    /**
     * Q10: Custom goals not in predefined list
     */
    company_goals_other?: string;
    /**
     * Q11: Desired brand tone and voice
     */
    brand_tone?: string;
    /**
     * Q11: Custom brand tone if 'Other' was selected
     */
    brand_tone_other?: string;
    /**
     * Q12.1: Certifications, awards, and partnerships (only if Q12 is yes)
     */
    certifications_partnerships?: {
      /**
       * Name of certification/partnership
       */
      cert_item_name?: string;
      /**
       * Type: certification, accolade, award, or partnership
       */
      cert_item_type?: string;
      /**
       * Badge or logo image URL
       */
      cert_item_image_url?: string;
      /**
       * Supporting document URL
       */
      cert_item_file_url?: string;
    }[];
    /**
     * Q13: Sales process and client onboarding
     */
    sales_process?: string;
    /**
     * Q14: If true, the company offers service guarantees/warranties/SLAs. If false, they do not.
     */
    service_guarantee?: boolean;
    /**
     * Q14.1: Service guarantees, warranties, and SLAs (only if service_guarantee is true)
     */
    service_guarantee_items?: {
      /**
       * Name of the guarantee
       */
      guarantee_name?: string;
      /**
       * Type: warranty, guarantee, or sla
       */
      guarantee_type?: string;
      /**
       * Supporting document URL
       */
      guarantee_file_url?: string;
      /**
       * Description of the guarantee
       */
      guarantee_description?: string;
    }[];
    /**
     * Q15: How the company currently acquires clients
     */
    client_acquisition?: string;
    /**
     * Q15: Custom acquisition method if 'Other' was selected
     */
    client_acquisition_other?: string;
    /**
     * Q16: Primary objectives for the website
     */
    website_objectives?: string[];
    /**
     * Q16: Custom objectives not in predefined list
     */
    website_objectives_other?: string;
    /**
     * Q17: Typical client company size (e.g., '10-100 employees')
     */
    client_size?: string;
    /**
     * Q18: Challenges that ideal clients face
     */
    client_challenges?: string[];
    /**
     * Q18: Custom challenges not in predefined list
     */
    client_challenges_other?: string;
    /**
     * Q19: Client frustrations and pain points
     */
    client_frustrations?: string;
    /**
     * Q20: Desired outcomes for clients
     */
    client_outcomes?: string[];
    /**
     * Q20: Custom outcomes not in predefined list
     */
    client_outcomes_other?: string;
    /**
     * Q21: How the company delivers value to clients
     */
    value_description?: string;
    /**
     * Q22: Description of the ideal client profile
     */
    ideal_client?: string;
    /**
     * Q23.1: Types of clients to avoid (only if Q23 is yes)
     */
    avoided_clients?: string;
    /**
     * Q24: Primary call-to-action for the website
     */
    primary_cta?: string;
    /**
     * Q24: Custom CTA if 'Other' was selected
     */
    primary_cta_other?: string;
    /**
     * Q25.1: Additional notes or instructions (only if Q25 is yes)
     */
    additional_notes?: string;
  };
}

export interface ProFormSubmissionIntake {
  /**
   * Questionnaire session identifier used for recovery and deduplication
   */
  questionnaire_session_id: string;
  business_name?: string;
  business_domain?: string;
  user_email?: string;
  user_id?: string;
  status?: "submitted" | "received_intake" | "retry_pending" | "retry_success" | "retry_failed" | "abandoned";
  intake_reason?: string;
  primary_failure_kind?: string;
  fallback_failure_kind?: string;
  primary_error_json?: string;
  fallback_error_json?: string;
  retry_error_json?: string;
  transformed_payload_json?: string;
  raw_responses_json?: string;
  diagnostics_json?: string;
  source?: string;
  created_at_client?: string;
  created_at_server?: string;
  last_retry_at?: string;
  retry_count?: number;
  linked_submission_id?: string;
  zapier_sent?: boolean;
  notes?: string;
  /**
   * Current AI repair lifecycle status (e.g. pending, running, completed, failed, skipped)
   */
  ai_repair_status?: string;
  /**
   * Number of AI repair attempts made for this intake record
   */
  ai_repair_attempt_count?: number;
  /**
   * ISO timestamp of the most recent AI repair attempt
   */
  last_ai_repair_at?: string;
  /**
   * Serialized error details if the AI repair attempt itself failed
   */
  ai_repair_error_json?: string;
  /**
   * Full JSON report returned by the pro_submission_repair_agent (decision, diagnosis, changed_paths, warnings, etc.)
   */
  ai_repair_report_json?: string;
  /**
   * Serialized repaired payload produced by the pro_submission_repair_agent
   */
  ai_repaired_payload_json?: string;
  /**
   * True if the AI-repaired payload was accepted and used in a submission attempt
   */
  ai_repair_applied?: boolean;
  /**
   * True if a submission retry was attempted using the AI-repaired payload
   */
  ai_repair_retry_attempted?: boolean;
  /**
   * Serialized result of the submission retry that used the AI-repaired payload
   */
  ai_repair_retry_result_json?: string;
  /**
   * Source context that triggered the AI repair (e.g. admin_manual, scheduled_job, retry_hook)
   */
  ai_repair_source?: string;
  /**
   * When this intake was moved out of the active recovery dataset
   */
  archived_at?: string;
  /**
   * Policy or administrator reason for archiving this intake
   */
  archive_reason?: string;
}

export interface QuestionnairePdfVersion {
  /**
   * Record type used to generate this PDF
   */
  source_type: "draft" | "intake" | "submission";
  /**
   * ID of the draft, intake, or final submission
   */
  source_id: string;
  /**
   * Questionnaire session identifier when available
   */
  session_id?: string;
  /**
   * SHA-256 fingerprint of the values rendered into this PDF
   */
  payload_hash: string;
  /**
   * Saved Base44 public-storage URL for the generated PDF
   */
  file_url: string;
  /**
   * Download filename for the generated PDF
   */
  file_name: string;
  /**
   * Monotonically increasing version number within the source record
   */
  version_number: number;
  /**
   * Business name shown in the PDF
   */
  business_name?: string;
  /**
   * Business domain shown in the PDF
   */
  domain?: string;
  /**
   * When this PDF version was generated
   */
  generated_at: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "ProFormDraft": ProFormDraft;
    "ProFormDraftEvent": ProFormDraftEvent;
    "ProFormSubmission": ProFormSubmission;
    "ProFormSubmissionIntake": ProFormSubmissionIntake;
    "QuestionnairePdfVersion": QuestionnairePdfVersion;
  }
  
  interface FunctionNameRegistry {
    "archiveRecoveryRecords": true;
    "generateAIContentOpenAI": true;
    "generateAIContent": true;
    "queryDraftRecoveryRecords": true;
    "manageQuestionnairePdfVersions": true;
    "repairProQuestionnaireIntakeSubmission": true;
    "retryProQuestionnaireIntakeSubmission": true;
    "sendToZapier": true;
    "submitProQuestionnaireFallback": true;
    "validateQuestionText": true;
    "verifyDraftRecoveryAccess": true;
    "_shared/base44Agent": true;
    "_shared/proSubmissionRepair": true;
    "retryProQuestionnaireIntakeSubmission/entry": true;
    "sendToZapier/entry": true;
    "submitProQuestionnaireFallback/entry": true;
  }
  
  interface AgentNameRegistry {
    "form_qa_validator": true;
    "msp_content_strategist": true;
    "pro_submission_repair_agent": true;
  }
}