import { createClientFromRequest } from 'npm:@base44/sdk';
import { ADMIN_API_OPERATION_NAMES, createAdminFunctionHandler } from '../_shared/proDraftAdminRequest/entry.ts';
import { PRO_DRAFT_API_VERSION } from '../_shared/proDraftApi/entry.ts';
import { PRO_DRAFT_CODE_RECOVERY_VERSION } from '../_shared/proDraftCodeRecovery/entry.ts';
import { PRO_DRAFT_ADMIN_AUTH_VERSION } from '../_shared/proDraftAdminAuthorization/entry.ts';
import { PRO_DRAFT_OPERATIONAL_EVENT_VERSION, aggregateOperationalSummary } from '../_shared/proDraftOperationalEvents/entry.ts';
import { buildHealthComponentResult, getSafeAdminHealthProjection } from '../_shared/proDraftHealth/entry.ts';
import { getBackendRuntimeConfig } from '../_shared/proDraftRuntimeConfig/entry.ts';
import { getSafeEmailTransportDiagnostics } from '../_shared/proDraftEmailTransport/entry.ts';
import { getExternalSideEffectPolicy } from '../_shared/proExternalSideEffects/entry.ts';

const REQUIRED_SECRETS = ['PRO_FORM_DRAFT_TOKEN_SECRET', 'PRO_FORM_RECOVERY_CODE_SECRET', 'PRO_FORM_RECOVERY_SESSION_SECRET', 'PRO_FORM_ADMIN_GRANT_SECRET', 'PRO_FORM_OPERATIONAL_FINGERPRINT_SECRET', 'PRO_FORM_SYNTHETIC_PROBE_SECRET'];
const safeDate = (value: unknown) => typeof value === 'string' && !Number.isNaN(Date.parse(value));
export function buildSecretPresence(getValue: (name: string) => string | undefined) { return Object.freeze(Object.fromEntries(REQUIRED_SECRETS.map((name) => [name, typeof getValue(name) === 'string' && new TextEncoder().encode(getValue(name)!).byteLength >= 32]))); }

export function createGetProDraftAdminHealthHandler(deps: Readonly<{createClientFromRequest: typeof createClientFromRequest; getEnvironmentValue: (name: string) => string | undefined; now?: () => Date}>) {
  return createAdminFunctionHandler({operation: ADMIN_API_OPERATION_NAMES.LIST_EVENTS, maxBytes: 16 * 1024, createClientFromRequest: deps.createClientFromRequest, getEnvironmentValue: deps.getEnvironmentValue, execute: async ({client, authorization, payload}) => {
    const now = deps.now?.() ?? new Date(); const checkedAt = now.toISOString(); const runtime = getBackendRuntimeConfig(deps.getEnvironmentValue); const entities = client.asServiceRole?.entities as Record<string, any>;
    const operational = entities?.ProFormOperationalEvent; const drafts = entities?.ProFormDraft; const conflicts = entities?.ProFormMigrationConflict; const checkpoints = entities?.ProFormMigrationCheckpoint;
    const since = new Date(now.getTime() - 15 * 60_000).toISOString();
    const criticalOffset = payload.criticalOffset === undefined ? 0 : Number.isSafeInteger(payload.criticalOffset) && Number(payload.criticalOffset) >= 0 && Number(payload.criticalOffset) <= 10000 ? Number(payload.criticalOffset) : 0;
    const rows = operational?.filter ? await operational.filter({environment: authorization.environment}, '-created_at_server', 1000, 0, ['event_type', 'severity', 'status', 'latency_ms', 'retry_count', 'created_at_server', 'test_run_id', 'error_code']) : [];
    const criticalRows = operational?.filter ? await operational.filter({environment: authorization.environment, severity: 'critical'}, '-created_at_server', 21, criticalOffset, ['event_type', 'severity', 'status', 'request_id', 'draft_fingerprint', 'created_at_server', 'error_code']) : [];
    const recent = rows.filter((row: Record<string, unknown>) => safeDate(row.created_at_server) && Date.parse(row.created_at_server as string) >= Date.parse(since)); const summary = aggregateOperationalSummary(recent);
    const [openConflicts, pendingReplacements, retentionRuns] = await Promise.all([conflicts?.filter ? conflicts.filter({environment: authorization.environment, status: 'open'}, '-detected_at', 100, 0, ['id']) : [], drafts?.filter ? drafts.filter({environment: authorization.environment, replacement_transaction_status: 'pending'}, '-replacement_transaction_started_at', 100, 0, ['id']) : [], checkpoints?.filter ? checkpoints.filter({environment: authorization.environment, migration_name: 'pro_form_draft_retention'}, '-updated_at', 1, 0, ['status', 'updated_at']) : []]);
    const lastProbe = rows.find((row: Record<string, unknown>) => row.event_type === 'synthetic_probe'); const email = getSafeEmailTransportDiagnostics({envSource: deps.getEnvironmentValue, environment: runtime.environment}); const external = getExternalSideEffectPolicy('zapier', {runtimeConfig: runtime}); const secrets = buildSecretPresence(deps.getEnvironmentValue);
    const components = [
      buildHealthComponentResult({component: 'runtime_config', status: runtime.durableDraftV2Enabled ? 'healthy' : runtime.configurationValid ? 'disabled' : 'unhealthy', checkedAt, details: {configured: runtime.configurationValid, enabled: runtime.durableDraftV2Enabled}}),
      ...['draft_bootstrap', 'draft_save', 'draft_load'].map((component) => buildHealthComponentResult({component: component as any, status: runtime.durableDraftV2Enabled ? 'healthy' : 'disabled', checkedAt, details: {version: PRO_DRAFT_API_VERSION}})),
      buildHealthComponentResult({component: 'public_recovery', status: runtime.publicEmailRecoveryEnabled ? 'healthy' : 'disabled', checkedAt, details: {version: PRO_DRAFT_CODE_RECOVERY_VERSION, enabled: runtime.publicEmailRecoveryEnabled}}),
      buildHealthComponentResult({component: 'admin_recovery', status: secrets.PRO_FORM_ADMIN_GRANT_SECRET ? 'healthy' : 'unhealthy', checkedAt, details: {version: PRO_DRAFT_ADMIN_AUTH_VERSION, configured: secrets.PRO_FORM_ADMIN_GRANT_SECRET}}),
      buildHealthComponentResult({component: 'operational_events', status: operational?.filter ? 'healthy' : 'unhealthy', checkedAt, details: {version: PRO_DRAFT_OPERATIONAL_EVENT_VERSION, available: Boolean(operational?.filter), recentCriticalCount: summary.criticalCount}}),
      buildHealthComponentResult({component: 'ses', status: email.mode === 'disabled' ? 'disabled' : email.credentialsConfigured ? 'healthy' : 'degraded', checkedAt, details: {mode: String(email.mode), configured: Boolean(email.credentialsConfigured)}}),
      buildHealthComponentResult({component: 'external_submission', status: external.mode === 'disabled' ? 'disabled' : external.allowed ? 'healthy' : 'degraded', checkedAt, details: {mode: external.mode, configured: external.allowed}}),
      buildHealthComponentResult({component: 'pdf', status: 'healthy', checkedAt, details: {available: true}}),
      buildHealthComponentResult({component: 'migration', status: openConflicts.length ? 'degraded' : 'healthy', checkedAt, details: {configured: Boolean(deps.getEnvironmentValue('PRO_FORM_CROSS_APP_MIGRATION_SECRET')), pendingCount: openConflicts.length}}),
      buildHealthComponentResult({component: 'retention', status: retentionRuns[0]?.status === 'failed' ? 'degraded' : 'healthy', checkedAt, details: {configured: true, failureCount: retentionRuns[0]?.status === 'failed' ? 1 : 0}}),
      buildHealthComponentResult({component: 'database', status: drafts?.filter ? 'healthy' : 'unhealthy', checkedAt, details: {available: Boolean(drafts?.filter), pendingCount: pendingReplacements.length}}),
      buildHealthComponentResult({component: 'rls', status: summary.rlsCriticalFailures ? 'unhealthy' : 'unknown', checkedAt, details: {recentCriticalCount: summary.rlsCriticalFailures}}),
    ];
    const cleanupFailureCount = recent.filter((row: Record<string, unknown>) => row.error_code === 'CLEANUP_FAILED').length;
    return getSafeAdminHealthProjection({components, environment: authorization.environment, buildSha: runtime.buildSha, checkedAt, requestId: authorization.requestId, secrets, featureFlags: {durableDraftV2Enabled: runtime.durableDraftV2Enabled, killSwitchEnabled: runtime.killSwitchEnabled, publicEmailRecoveryEnabled: runtime.publicEmailRecoveryEnabled, emailOtpEnabled: runtime.emailOtpEnabled, magicLinkEnabled: runtime.magicLinkEnabled, diagnosticsEnabled: runtime.diagnosticsEnabled, externalSideEffectsMode: runtime.externalSideEffectsMode}, metrics: {saveP95LatencyMs: summary.latencyMs.p95, saveP99LatencyMs: summary.latencyMs.p99, saveFailureRate: summary.rates.saveFailure, recoveryFailureRate: summary.rates.recoveryFailure, conflictRate: summary.rates.conflict, submissionFailureRate: summary.rates.submissionFailure, sesFailureRate: summary.rates.sesFailure, recentCriticalCount: summary.criticalCount, pendingMigrationConflicts: openConflicts.length, pendingReplacementTransactions: pendingReplacements.length, cleanupFailureCount}, lastSyntheticProbe: lastProbe ? {status: lastProbe.status, checkedAt: lastProbe.created_at_server, errorCode: lastProbe.error_code ?? null} : null, criticalEvents: criticalRows.slice(0, 20).map((row: Record<string, unknown>) => ({eventType: row.event_type, severity: row.severity, status: row.status, requestId: row.request_id, draftFingerprint: row.draft_fingerprint, checkedAt: row.created_at_server, errorCode: row.error_code ?? null})), criticalPagination: {offset: criticalOffset, limit: 20, hasMore: criticalRows.length > 20}});
  }});
}
if (typeof Deno !== 'undefined') Deno.serve(createGetProDraftAdminHealthHandler({createClientFromRequest, getEnvironmentValue: (name) => Deno.env.get(name)}));
